baseurl: "/"
permalink: pretty
title: "CASYCON S.R.L."

logo:
  mobile: "images/logo/caribbean.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/caribbean.svg"
  desktop_height: "120px"
  desktop_width: "120px"

home:
  limit_services: 4

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: false
  partners:
    output: true
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
    style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
